import { Trip } from './types';

export const ALL_TRIPS_DATA: Trip[] = [
  {
    id: 17,
    title: "Randonnée Pédestre vers le Sommet de Lalla Khedidja",
    destination: "Lalla Khedidja, Djurdjura, Algérie",
    type: "Randonnée Pédestre",
    category: "Randonnée",
    purpose: "Randonnée de 18km pour atteindre le sommet de Lalla Khedidja, avec un dénivelé positif important. Une bonne condition physique est requise.",
    difficulty: 'Difficult',
    distance: 18,
    duration: "1 Jour",
    price: 2200,
    includes: ['Guide et assistance', 'Transport Aller-Retour'],
    departureTime: '06:00 Matin',
    returnTime: '19:00 Sur Alger',
    meetingPoint: "Grand parking de Ruisseau face Tribunal",
    equipment: ["Chaussures de marche robustes", "Vêtements adaptés", "Sac à dos", "Bouteille d’eau"],
    toBring: "Pique-nique à la charge du client.",
    serviceOffered: "Pique-nique en pleine nature, temps libre et relaxation.",
    rating: 4.9,
    reviewCount: 153,
    imageUrls: [
      'https://images.unsplash.com/photo-1542224562-2_741810265c79?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1542224562-82f42921a59b?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1588392382834-a891154bca4d?q=80&w=1600&h=900&fit=crop'
    ],
    isNextWeekend: true,
  },
  {
    id: 19,
    title: "Randonnée Télésiège Tikjda",
    destination: "Tikjda, Bouira, Algérie",
    type: "Randonnée Pédestre",
    category: "Randonnée",
    purpose: "Une randonnée facile pour visiter le sommet atteint par le télésiège de Tikjda, avec des vues panoramiques sur le Djurdjura.",
    difficulty: 'Easy',
    distance: 6,
    duration: "1 Jour",
    price: 1900,
    includes: ['Transport en bus confortable', 'Accompagnement et guide', 'Organisation de la randonnée'],
    departureTime: '06:00 Matin',
    returnTime: '18:00 Sur Alger',
    meetingPoint: "Grand parking de Ruisseau face Tribunal",
    equipment: ["Chaussures de marche adaptées", "Vêtements chauds", "Sac à dos", "Bouteille d'eau", "Tapis de sol"],
    toBring: "Déjeuner à la charge du client.",
    serviceOffered: "Visite du sommet du télésiège et pause déjeuner en nature.",
    rating: 4.8,
    reviewCount: 130,
    imageUrls: [
      'https://images.unsplash.com/photo-1604537466158-719b1972feb8?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1518244360993-21394f4ed135?q=80&w=1600&h=900&fit=crop'
    ],
    isNextWeekend: true,
  },
  {
    id: 20,
    title: "Randonnée au Lac Agulmim, Tikjda",
    destination: "Lac Agulmim, Tikjda, Algérie",
    type: "Randonnée Pédestre",
    category: "Randonnée",
    purpose: "Une randonnée difficile vers le magnifique lac d'altitude Agulmim, un défi pour les randonneurs expérimentés.",
    difficulty: 'Difficult',
    distance: 22,
    duration: "1 Jour",
    price: 2000,
    includes: ['Guide et assistance', 'Transport Aller-Retour'],
    departureTime: '06:00 Matin',
    returnTime: '19:00 Sur Alger',
    meetingPoint: "Grand parking de Ruisseau face Tribunal",
    equipment: ["Chaussures adéquates à la marche", "Sac à dos", "Bouteille d’eau", "Tapis de sols", "Gants et bonnet"],
    toBring: "Pique-nique au bord du lac.",
    serviceOffered: "Randonnée guidée de 22km et pique-nique au bord du lac.",
    rating: 4.9,
    reviewCount: 178,
    imageUrls: [
      'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1519993895692-5a823c91a355?q=80&w=1600&h=900&fit=crop'
    ],
    isNextWeekend: true,
  },
  {
    id: 21,
    title: "Bivouac sous les étoiles du Tassili n'Ajjer",
    destination: "Tassili n'Ajjer, Djanet, Algérie",
    type: "Expédition",
    category: "Bivouac",
    purpose: "Expérience immersive de bivouac dans le désert du Sahara, avec exploration des peintures rupestres et nuits à la belle étoile.",
    difficulty: 'Medium',
    distance: 50, // sur plusieurs jours
    duration: "3 Jours / 2 Nuits",
    price: 15000,
    includes: ['Guide local', 'Transport 4x4', 'Pension complète', 'Matériel de camping'],
    departureTime: '08:00 Jour 1',
    returnTime: '17:00 Jour 3',
    meetingPoint: "Aéroport de Djanet",
    equipment: ["Sac de couchage", "Vêtements pour climat désertique", "Lampe frontale", "Lunettes de soleil"],
    toBring: "Effets personnels et appareil photo.",
    serviceOffered: "Trekking, découverte de sites archéologiques, cuisine traditionnelle.",
    rating: 5.0,
    reviewCount: 210,
    imageUrls: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbb5b9?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1517824806714-231014f2433a?q=80&w=1600&h=900&fit=crop',
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=1600&h=900&fit=crop'
    ],
    isNextWeekend: true,
  }
];